/*
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.ui.tests;

import br.compiladores.jhonatan.jlanguage.ui.internal.JlanguageActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class JlanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JlanguageActivator.getInstance().getInjector("br.compiladores.jhonatan.jlanguage.Jlanguage");
	}

}
