/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage.impl;

import br.compiladores.jhonatan.jlanguage.jlanguage.ChamadaFuncao;
import br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoAritmetica;
import br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chamada Funcao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ChamadaFuncaoImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ChamadaFuncaoImpl#getArgumentos <em>Argumentos</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChamadaFuncaoImpl extends MinimalEObjectImpl.Container implements ChamadaFuncao
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getArgumentos() <em>Argumentos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgumentos()
   * @generated
   * @ordered
   */
  protected EList<ExpressaoAritmetica> argumentos;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChamadaFuncaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JlanguagePackage.Literals.CHAMADA_FUNCAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JlanguagePackage.CHAMADA_FUNCAO__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ExpressaoAritmetica> getArgumentos()
  {
    if (argumentos == null)
    {
      argumentos = new EObjectContainmentEList<ExpressaoAritmetica>(ExpressaoAritmetica.class, this, JlanguagePackage.CHAMADA_FUNCAO__ARGUMENTOS);
    }
    return argumentos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JlanguagePackage.CHAMADA_FUNCAO__ARGUMENTOS:
        return ((InternalEList<?>)getArgumentos()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JlanguagePackage.CHAMADA_FUNCAO__NAME:
        return getName();
      case JlanguagePackage.CHAMADA_FUNCAO__ARGUMENTOS:
        return getArgumentos();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JlanguagePackage.CHAMADA_FUNCAO__NAME:
        setName((String)newValue);
        return;
      case JlanguagePackage.CHAMADA_FUNCAO__ARGUMENTOS:
        getArgumentos().clear();
        getArgumentos().addAll((Collection<? extends ExpressaoAritmetica>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JlanguagePackage.CHAMADA_FUNCAO__NAME:
        setName(NAME_EDEFAULT);
        return;
      case JlanguagePackage.CHAMADA_FUNCAO__ARGUMENTOS:
        getArgumentos().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JlanguagePackage.CHAMADA_FUNCAO__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case JlanguagePackage.CHAMADA_FUNCAO__ARGUMENTOS:
        return argumentos != null && !argumentos.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ChamadaFuncaoImpl
