/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage.impl;

import br.compiladores.jhonatan.jlanguage.jlanguage.FatorAritmetico;
import br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fator Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FatorAritmeticoImpl extends MinimalEObjectImpl.Container implements FatorAritmetico
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FatorAritmeticoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JlanguagePackage.Literals.FATOR_ARITMETICO;
  }

} //FatorAritmeticoImpl
