/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage.impl;

import br.compiladores.jhonatan.jlanguage.jlanguage.Comando;
import br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao;
import br.compiladores.jhonatan.jlanguage.jlanguage.Funcao;
import br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Funcao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FuncaoImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FuncaoImpl#getParametros <em>Parametros</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FuncaoImpl#getTipo <em>Tipo</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FuncaoImpl#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FuncaoImpl extends MinimalEObjectImpl.Container implements Funcao
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParametros() <em>Parametros</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParametros()
   * @generated
   * @ordered
   */
  protected EList<Declaracao> parametros;

  /**
   * The default value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected static final String TIPO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTipo() <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected String tipo = TIPO_EDEFAULT;

  /**
   * The cached value of the '{@link #getComandos() <em>Comandos</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComandos()
   * @generated
   * @ordered
   */
  protected Comando comandos;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JlanguagePackage.Literals.FUNCAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JlanguagePackage.FUNCAO__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Declaracao> getParametros()
  {
    if (parametros == null)
    {
      parametros = new EObjectContainmentEList<Declaracao>(Declaracao.class, this, JlanguagePackage.FUNCAO__PARAMETROS);
    }
    return parametros;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTipo()
  {
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTipo(String newTipo)
  {
    String oldTipo = tipo;
    tipo = newTipo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JlanguagePackage.FUNCAO__TIPO, oldTipo, tipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Comando getComandos()
  {
    return comandos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetComandos(Comando newComandos, NotificationChain msgs)
  {
    Comando oldComandos = comandos;
    comandos = newComandos;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JlanguagePackage.FUNCAO__COMANDOS, oldComandos, newComandos);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setComandos(Comando newComandos)
  {
    if (newComandos != comandos)
    {
      NotificationChain msgs = null;
      if (comandos != null)
        msgs = ((InternalEObject)comandos).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JlanguagePackage.FUNCAO__COMANDOS, null, msgs);
      if (newComandos != null)
        msgs = ((InternalEObject)newComandos).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JlanguagePackage.FUNCAO__COMANDOS, null, msgs);
      msgs = basicSetComandos(newComandos, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JlanguagePackage.FUNCAO__COMANDOS, newComandos, newComandos));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JlanguagePackage.FUNCAO__PARAMETROS:
        return ((InternalEList<?>)getParametros()).basicRemove(otherEnd, msgs);
      case JlanguagePackage.FUNCAO__COMANDOS:
        return basicSetComandos(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JlanguagePackage.FUNCAO__NAME:
        return getName();
      case JlanguagePackage.FUNCAO__PARAMETROS:
        return getParametros();
      case JlanguagePackage.FUNCAO__TIPO:
        return getTipo();
      case JlanguagePackage.FUNCAO__COMANDOS:
        return getComandos();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JlanguagePackage.FUNCAO__NAME:
        setName((String)newValue);
        return;
      case JlanguagePackage.FUNCAO__PARAMETROS:
        getParametros().clear();
        getParametros().addAll((Collection<? extends Declaracao>)newValue);
        return;
      case JlanguagePackage.FUNCAO__TIPO:
        setTipo((String)newValue);
        return;
      case JlanguagePackage.FUNCAO__COMANDOS:
        setComandos((Comando)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JlanguagePackage.FUNCAO__NAME:
        setName(NAME_EDEFAULT);
        return;
      case JlanguagePackage.FUNCAO__PARAMETROS:
        getParametros().clear();
        return;
      case JlanguagePackage.FUNCAO__TIPO:
        setTipo(TIPO_EDEFAULT);
        return;
      case JlanguagePackage.FUNCAO__COMANDOS:
        setComandos((Comando)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JlanguagePackage.FUNCAO__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case JlanguagePackage.FUNCAO__PARAMETROS:
        return parametros != null && !parametros.isEmpty();
      case JlanguagePackage.FUNCAO__TIPO:
        return TIPO_EDEFAULT == null ? tipo != null : !TIPO_EDEFAULT.equals(tipo);
      case JlanguagePackage.FUNCAO__COMANDOS:
        return comandos != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", tipo: ");
    result.append(tipo);
    result.append(')');
    return result.toString();
  }

} //FuncaoImpl
