/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage.impl;

import br.compiladores.jhonatan.jlanguage.jlanguage.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class JlanguageFactoryImpl extends EFactoryImpl implements JlanguageFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static JlanguageFactory init()
  {
    try
    {
      JlanguageFactory theJlanguageFactory = (JlanguageFactory)EPackage.Registry.INSTANCE.getEFactory(JlanguagePackage.eNS_URI);
      if (theJlanguageFactory != null)
      {
        return theJlanguageFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new JlanguageFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JlanguageFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case JlanguagePackage.PROGRAMA: return createPrograma();
      case JlanguagePackage.DECLARACAO: return createDeclaracao();
      case JlanguagePackage.EXPRESSAO_ARITMETICA: return createExpressaoAritmetica();
      case JlanguagePackage.OUTRO_TERMO_ARITMETICO: return createOutroTermoAritmetico();
      case JlanguagePackage.TERMO_ARITMETICO: return createTermoAritmetico();
      case JlanguagePackage.OUTRO_FATOR_ARITMETICO: return createOutroFatorAritmetico();
      case JlanguagePackage.FATOR_ARITMETICO: return createFatorAritmetico();
      case JlanguagePackage.FATOR_NUMERO: return createFatorNumero();
      case JlanguagePackage.FATOR_VARIAVEL: return createFatorVariavel();
      case JlanguagePackage.FATOR_SUB_EXPRESSAO: return createFatorSubExpressao();
      case JlanguagePackage.EXPRESSAO_RELACIONAL: return createExpressaoRelacional();
      case JlanguagePackage.OUTRO_TERMO_RELACIONAL: return createOutroTermoRelacional();
      case JlanguagePackage.TERMO_RELACIONAL: return createTermoRelacional();
      case JlanguagePackage.TERMO_COMPARACAO_RELACIONAL: return createTermoComparacaoRelacional();
      case JlanguagePackage.TERMO_SUB_EXPRESSAO_RELACIONAL: return createTermoSubExpressaoRelacional();
      case JlanguagePackage.COMANDO: return createComando();
      case JlanguagePackage.COMANDO_ATIBUICAO: return createComandoAtibuicao();
      case JlanguagePackage.COMANDO_ENTRADA: return createComandoEntrada();
      case JlanguagePackage.COMANDO_SAIDA: return createComandoSaida();
      case JlanguagePackage.COMANDO_CONDICAO: return createComandoCondicao();
      case JlanguagePackage.COMANDO_REPETICAO: return createComandoRepeticao();
      case JlanguagePackage.COMANDO_SUB_ALGORITMO: return createComandoSubAlgoritmo();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Programa createPrograma()
  {
    ProgramaImpl programa = new ProgramaImpl();
    return programa;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Declaracao createDeclaracao()
  {
    DeclaracaoImpl declaracao = new DeclaracaoImpl();
    return declaracao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoAritmetica createExpressaoAritmetica()
  {
    ExpressaoAritmeticaImpl expressaoAritmetica = new ExpressaoAritmeticaImpl();
    return expressaoAritmetica;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutroTermoAritmetico createOutroTermoAritmetico()
  {
    OutroTermoAritmeticoImpl outroTermoAritmetico = new OutroTermoAritmeticoImpl();
    return outroTermoAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoAritmetico createTermoAritmetico()
  {
    TermoAritmeticoImpl termoAritmetico = new TermoAritmeticoImpl();
    return termoAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutroFatorAritmetico createOutroFatorAritmetico()
  {
    OutroFatorAritmeticoImpl outroFatorAritmetico = new OutroFatorAritmeticoImpl();
    return outroFatorAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorAritmetico createFatorAritmetico()
  {
    FatorAritmeticoImpl fatorAritmetico = new FatorAritmeticoImpl();
    return fatorAritmetico;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorNumero createFatorNumero()
  {
    FatorNumeroImpl fatorNumero = new FatorNumeroImpl();
    return fatorNumero;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorVariavel createFatorVariavel()
  {
    FatorVariavelImpl fatorVariavel = new FatorVariavelImpl();
    return fatorVariavel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FatorSubExpressao createFatorSubExpressao()
  {
    FatorSubExpressaoImpl fatorSubExpressao = new FatorSubExpressaoImpl();
    return fatorSubExpressao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressaoRelacional createExpressaoRelacional()
  {
    ExpressaoRelacionalImpl expressaoRelacional = new ExpressaoRelacionalImpl();
    return expressaoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OutroTermoRelacional createOutroTermoRelacional()
  {
    OutroTermoRelacionalImpl outroTermoRelacional = new OutroTermoRelacionalImpl();
    return outroTermoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoRelacional createTermoRelacional()
  {
    TermoRelacionalImpl termoRelacional = new TermoRelacionalImpl();
    return termoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoComparacaoRelacional createTermoComparacaoRelacional()
  {
    TermoComparacaoRelacionalImpl termoComparacaoRelacional = new TermoComparacaoRelacionalImpl();
    return termoComparacaoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TermoSubExpressaoRelacional createTermoSubExpressaoRelacional()
  {
    TermoSubExpressaoRelacionalImpl termoSubExpressaoRelacional = new TermoSubExpressaoRelacionalImpl();
    return termoSubExpressaoRelacional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Comando createComando()
  {
    ComandoImpl comando = new ComandoImpl();
    return comando;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoAtibuicao createComandoAtibuicao()
  {
    ComandoAtibuicaoImpl comandoAtibuicao = new ComandoAtibuicaoImpl();
    return comandoAtibuicao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoEntrada createComandoEntrada()
  {
    ComandoEntradaImpl comandoEntrada = new ComandoEntradaImpl();
    return comandoEntrada;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoSaida createComandoSaida()
  {
    ComandoSaidaImpl comandoSaida = new ComandoSaidaImpl();
    return comandoSaida;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoCondicao createComandoCondicao()
  {
    ComandoCondicaoImpl comandoCondicao = new ComandoCondicaoImpl();
    return comandoCondicao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoRepeticao createComandoRepeticao()
  {
    ComandoRepeticaoImpl comandoRepeticao = new ComandoRepeticaoImpl();
    return comandoRepeticao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComandoSubAlgoritmo createComandoSubAlgoritmo()
  {
    ComandoSubAlgoritmoImpl comandoSubAlgoritmo = new ComandoSubAlgoritmoImpl();
    return comandoSubAlgoritmo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JlanguagePackage getJlanguagePackage()
  {
    return (JlanguagePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static JlanguagePackage getPackage()
  {
    return JlanguagePackage.eINSTANCE;
  }

} //JlanguageFactoryImpl
