/*
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JlanguageRuntimeModule extends AbstractJlanguageRuntimeModule {
}
