/*
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.ide.contentassist.antlr;

import br.compiladores.jhonatan.jlanguage.ide.contentassist.antlr.internal.InternalJlanguageParser;
import br.compiladores.jhonatan.jlanguage.services.JlanguageGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class JlanguageParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(JlanguageGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, JlanguageGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFatorAritmeticoAccess().getAlternatives(), "rule__FatorAritmetico__Alternatives");
			builder.put(grammarAccess.getTermoRelacionalAccess().getAlternatives(), "rule__TermoRelacional__Alternatives");
			builder.put(grammarAccess.getComandoAccess().getAlternatives(), "rule__Comando__Alternatives");
			builder.put(grammarAccess.getTipoVarAccess().getAlternatives(), "rule__TipoVar__Alternatives");
			builder.put(grammarAccess.getOpArit1Access().getAlternatives(), "rule__OpArit1__Alternatives");
			builder.put(grammarAccess.getOpArit2Access().getAlternatives(), "rule__OpArit2__Alternatives");
			builder.put(grammarAccess.getOpRelAccess().getAlternatives(), "rule__OpRel__Alternatives");
			builder.put(grammarAccess.getOpBoolAccess().getAlternatives(), "rule__OpBool__Alternatives");
			builder.put(grammarAccess.getProgramaAccess().getGroup(), "rule__Programa__Group__0");
			builder.put(grammarAccess.getDeclaracaoAccess().getGroup(), "rule__Declaracao__Group__0");
			builder.put(grammarAccess.getExpressaoAritmeticaAccess().getGroup(), "rule__ExpressaoAritmetica__Group__0");
			builder.put(grammarAccess.getOutroTermoAritmeticoAccess().getGroup(), "rule__OutroTermoAritmetico__Group__0");
			builder.put(grammarAccess.getTermoAritmeticoAccess().getGroup(), "rule__TermoAritmetico__Group__0");
			builder.put(grammarAccess.getOutroFatorAritmeticoAccess().getGroup(), "rule__OutroFatorAritmetico__Group__0");
			builder.put(grammarAccess.getFatorSubExpressaoAccess().getGroup(), "rule__FatorSubExpressao__Group__0");
			builder.put(grammarAccess.getExpressaoRelacionalAccess().getGroup(), "rule__ExpressaoRelacional__Group__0");
			builder.put(grammarAccess.getOutroTermoRelacionalAccess().getGroup(), "rule__OutroTermoRelacional__Group__0");
			builder.put(grammarAccess.getTermoComparacaoRelacionalAccess().getGroup(), "rule__TermoComparacaoRelacional__Group__0");
			builder.put(grammarAccess.getTermoSubExpressaoRelacionalAccess().getGroup(), "rule__TermoSubExpressaoRelacional__Group__0");
			builder.put(grammarAccess.getComandoAtibuicaoAccess().getGroup(), "rule__ComandoAtibuicao__Group__0");
			builder.put(grammarAccess.getComandoEntradaAccess().getGroup(), "rule__ComandoEntrada__Group__0");
			builder.put(grammarAccess.getComandoSaidaAccess().getGroup(), "rule__ComandoSaida__Group__0");
			builder.put(grammarAccess.getComandoCondicaoAccess().getGroup(), "rule__ComandoCondicao__Group__0");
			builder.put(grammarAccess.getComandoCondicaoAccess().getGroup_4(), "rule__ComandoCondicao__Group_4__0");
			builder.put(grammarAccess.getComandoRepeticaoAccess().getGroup(), "rule__ComandoRepeticao__Group__0");
			builder.put(grammarAccess.getComandoSubAlgoritmoAccess().getGroup(), "rule__ComandoSubAlgoritmo__Group__0");
			builder.put(grammarAccess.getChamadaFuncaoAccess().getGroup(), "rule__ChamadaFuncao__Group__0");
			builder.put(grammarAccess.getChamadaFuncaoAccess().getGroup_2(), "rule__ChamadaFuncao__Group_2__0");
			builder.put(grammarAccess.getChamadaFuncaoAccess().getGroup_2_1(), "rule__ChamadaFuncao__Group_2_1__0");
			builder.put(grammarAccess.getFuncaoAccess().getGroup(), "rule__Funcao__Group__0");
			builder.put(grammarAccess.getFuncaoAccess().getGroup_3(), "rule__Funcao__Group_3__0");
			builder.put(grammarAccess.getFuncaoAccess().getGroup_3_1(), "rule__Funcao__Group_3_1__0");
			builder.put(grammarAccess.getProgramaAccess().getDeclaracoesAssignment_2(), "rule__Programa__DeclaracoesAssignment_2");
			builder.put(grammarAccess.getProgramaAccess().getComandosAssignment_5(), "rule__Programa__ComandosAssignment_5");
			builder.put(grammarAccess.getDeclaracaoAccess().getNameAssignment_0(), "rule__Declaracao__NameAssignment_0");
			builder.put(grammarAccess.getDeclaracaoAccess().getTipoAssignment_2(), "rule__Declaracao__TipoAssignment_2");
			builder.put(grammarAccess.getExpressaoAritmeticaAccess().getTermo1Assignment_0(), "rule__ExpressaoAritmetica__Termo1Assignment_0");
			builder.put(grammarAccess.getExpressaoAritmeticaAccess().getOutrosTermosAssignment_1(), "rule__ExpressaoAritmetica__OutrosTermosAssignment_1");
			builder.put(grammarAccess.getOutroTermoAritmeticoAccess().getOperadorAssignment_0(), "rule__OutroTermoAritmetico__OperadorAssignment_0");
			builder.put(grammarAccess.getOutroTermoAritmeticoAccess().getTermoAssignment_1(), "rule__OutroTermoAritmetico__TermoAssignment_1");
			builder.put(grammarAccess.getTermoAritmeticoAccess().getFator1Assignment_0(), "rule__TermoAritmetico__Fator1Assignment_0");
			builder.put(grammarAccess.getTermoAritmeticoAccess().getOutrosFatoresAssignment_1(), "rule__TermoAritmetico__OutrosFatoresAssignment_1");
			builder.put(grammarAccess.getOutroFatorAritmeticoAccess().getOperadorAssignment_0(), "rule__OutroFatorAritmetico__OperadorAssignment_0");
			builder.put(grammarAccess.getOutroFatorAritmeticoAccess().getFatorAssignment_1(), "rule__OutroFatorAritmetico__FatorAssignment_1");
			builder.put(grammarAccess.getFatorNumeroAccess().getNumeroAssignment(), "rule__FatorNumero__NumeroAssignment");
			builder.put(grammarAccess.getFatorVariavelAccess().getVariavelAssignment(), "rule__FatorVariavel__VariavelAssignment");
			builder.put(grammarAccess.getFatorSubExpressaoAccess().getExpressaoAssignment_1(), "rule__FatorSubExpressao__ExpressaoAssignment_1");
			builder.put(grammarAccess.getExpressaoRelacionalAccess().getTermo1Assignment_0(), "rule__ExpressaoRelacional__Termo1Assignment_0");
			builder.put(grammarAccess.getExpressaoRelacionalAccess().getOutrosTermosAssignment_1(), "rule__ExpressaoRelacional__OutrosTermosAssignment_1");
			builder.put(grammarAccess.getOutroTermoRelacionalAccess().getOperadorAssignment_0(), "rule__OutroTermoRelacional__OperadorAssignment_0");
			builder.put(grammarAccess.getOutroTermoRelacionalAccess().getTermoAssignment_1(), "rule__OutroTermoRelacional__TermoAssignment_1");
			builder.put(grammarAccess.getTermoComparacaoRelacionalAccess().getExpr1Assignment_0(), "rule__TermoComparacaoRelacional__Expr1Assignment_0");
			builder.put(grammarAccess.getTermoComparacaoRelacionalAccess().getOpRelAssignment_1(), "rule__TermoComparacaoRelacional__OpRelAssignment_1");
			builder.put(grammarAccess.getTermoComparacaoRelacionalAccess().getExpr2Assignment_2(), "rule__TermoComparacaoRelacional__Expr2Assignment_2");
			builder.put(grammarAccess.getTermoSubExpressaoRelacionalAccess().getExpRelAssignment_1(), "rule__TermoSubExpressaoRelacional__ExpRelAssignment_1");
			builder.put(grammarAccess.getComandoAtibuicaoAccess().getExpAssignment_1(), "rule__ComandoAtibuicao__ExpAssignment_1");
			builder.put(grammarAccess.getComandoAtibuicaoAccess().getVariavelAssignment_3(), "rule__ComandoAtibuicao__VariavelAssignment_3");
			builder.put(grammarAccess.getComandoEntradaAccess().getVariavelAssignment_1(), "rule__ComandoEntrada__VariavelAssignment_1");
			builder.put(grammarAccess.getComandoSaidaAccess().getVariavelAssignment_1(), "rule__ComandoSaida__VariavelAssignment_1");
			builder.put(grammarAccess.getComandoCondicaoAccess().getExpAssignment_1(), "rule__ComandoCondicao__ExpAssignment_1");
			builder.put(grammarAccess.getComandoCondicaoAccess().getCmd1Assignment_3(), "rule__ComandoCondicao__Cmd1Assignment_3");
			builder.put(grammarAccess.getComandoCondicaoAccess().getCmd2Assignment_4_1(), "rule__ComandoCondicao__Cmd2Assignment_4_1");
			builder.put(grammarAccess.getComandoRepeticaoAccess().getExpAssignment_1(), "rule__ComandoRepeticao__ExpAssignment_1");
			builder.put(grammarAccess.getComandoRepeticaoAccess().getCmdAssignment_2(), "rule__ComandoRepeticao__CmdAssignment_2");
			builder.put(grammarAccess.getComandoSubAlgoritmoAccess().getComandosAssignment_1(), "rule__ComandoSubAlgoritmo__ComandosAssignment_1");
			builder.put(grammarAccess.getChamadaFuncaoAccess().getNameAssignment_0(), "rule__ChamadaFuncao__NameAssignment_0");
			builder.put(grammarAccess.getChamadaFuncaoAccess().getArgumentosAssignment_2_0(), "rule__ChamadaFuncao__ArgumentosAssignment_2_0");
			builder.put(grammarAccess.getChamadaFuncaoAccess().getArgumentosAssignment_2_1_1(), "rule__ChamadaFuncao__ArgumentosAssignment_2_1_1");
			builder.put(grammarAccess.getFuncaoAccess().getNameAssignment_1(), "rule__Funcao__NameAssignment_1");
			builder.put(grammarAccess.getFuncaoAccess().getParametrosAssignment_3_0(), "rule__Funcao__ParametrosAssignment_3_0");
			builder.put(grammarAccess.getFuncaoAccess().getParametrosAssignment_3_1_1(), "rule__Funcao__ParametrosAssignment_3_1_1");
			builder.put(grammarAccess.getFuncaoAccess().getTipoAssignment_6(), "rule__Funcao__TipoAssignment_6");
			builder.put(grammarAccess.getFuncaoAccess().getComandosAssignment_7(), "rule__Funcao__ComandosAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private JlanguageGrammarAccess grammarAccess;

	@Override
	protected InternalJlanguageParser createParser() {
		InternalJlanguageParser result = new InternalJlanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public JlanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JlanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
