/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando Saida</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSaida#getVariavel <em>Variavel</em>}</li>
 * </ul>
 *
 * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getComandoSaida()
 * @model
 * @generated
 */
public interface ComandoSaida extends Comando
{
  /**
   * Returns the value of the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variavel</em>' reference.
   * @see #setVariavel(Declaracao)
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getComandoSaida_Variavel()
   * @model
   * @generated
   */
  Declaracao getVariavel();

  /**
   * Sets the value of the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSaida#getVariavel <em>Variavel</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variavel</em>' reference.
   * @see #getVariavel()
   * @generated
   */
  void setVariavel(Declaracao value);

} // ComandoSaida
