/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao Relacional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional#getTermo1 <em>Termo1</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional#getOutrosTermos <em>Outros Termos</em>}</li>
 * </ul>
 *
 * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getExpressaoRelacional()
 * @model
 * @generated
 */
public interface ExpressaoRelacional extends EObject
{
  /**
   * Returns the value of the '<em><b>Termo1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termo1</em>' containment reference.
   * @see #setTermo1(TermoRelacional)
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getExpressaoRelacional_Termo1()
   * @model containment="true"
   * @generated
   */
  TermoRelacional getTermo1();

  /**
   * Sets the value of the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional#getTermo1 <em>Termo1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Termo1</em>' containment reference.
   * @see #getTermo1()
   * @generated
   */
  void setTermo1(TermoRelacional value);

  /**
   * Returns the value of the '<em><b>Outros Termos</b></em>' containment reference list.
   * The list contents are of type {@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outros Termos</em>' containment reference list.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getExpressaoRelacional_OutrosTermos()
   * @model containment="true"
   * @generated
   */
  EList<OutroTermoRelacional> getOutrosTermos();

} // ExpressaoRelacional
