/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fator Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getFatorAritmetico()
 * @model
 * @generated
 */
public interface FatorAritmetico extends EObject
{
} // FatorAritmetico
