/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Funcao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getName <em>Name</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getParametros <em>Parametros</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getTipo <em>Tipo</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getFuncao()
 * @model
 * @generated
 */
public interface Funcao extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getFuncao_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parametros</b></em>' containment reference list.
   * The list contents are of type {@link br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametros</em>' containment reference list.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getFuncao_Parametros()
   * @model containment="true"
   * @generated
   */
  EList<Declaracao> getParametros();

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getFuncao_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

  /**
   * Returns the value of the '<em><b>Comandos</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos</em>' containment reference.
   * @see #setComandos(Comando)
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getFuncao_Comandos()
   * @model containment="true"
   * @generated
   */
  Comando getComandos();

  /**
   * Sets the value of the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getComandos <em>Comandos</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comandos</em>' containment reference.
   * @see #getComandos()
   * @generated
   */
  void setComandos(Comando value);

} // Funcao
