/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguageFactory
 * @model kind="package"
 * @generated
 */
public interface JlanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "jlanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.compiladores.br/jhonatan/jlanguage/Jlanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "jlanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JlanguagePackage eINSTANCE = br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ProgramaImpl <em>Programa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ProgramaImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getPrograma()
   * @generated
   */
  int PROGRAMA = 0;

  /**
   * The feature id for the '<em><b>Declaracoes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__DECLARACOES = 0;

  /**
   * The feature id for the '<em><b>Comandos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__COMANDOS = 1;

  /**
   * The number of structural features of the '<em>Programa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.DeclaracaoImpl <em>Declaracao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.DeclaracaoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getDeclaracao()
   * @generated
   */
  int DECLARACAO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__NAME = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO__TIPO = 1;

  /**
   * The number of structural features of the '<em>Declaracao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACAO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ExpressaoAritmeticaImpl <em>Expressao Aritmetica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ExpressaoAritmeticaImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getExpressaoAritmetica()
   * @generated
   */
  int EXPRESSAO_ARITMETICA = 2;

  /**
   * The feature id for the '<em><b>Termo1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA__TERMO1 = 0;

  /**
   * The feature id for the '<em><b>Outros Termos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA__OUTROS_TERMOS = 1;

  /**
   * The number of structural features of the '<em>Expressao Aritmetica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_ARITMETICA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroTermoAritmeticoImpl <em>Outro Termo Aritmetico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroTermoAritmeticoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getOutroTermoAritmetico()
   * @generated
   */
  int OUTRO_TERMO_ARITMETICO = 3;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_ARITMETICO__OPERADOR = 0;

  /**
   * The feature id for the '<em><b>Termo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_ARITMETICO__TERMO = 1;

  /**
   * The number of structural features of the '<em>Outro Termo Aritmetico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_ARITMETICO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoAritmeticoImpl <em>Termo Aritmetico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoAritmeticoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getTermoAritmetico()
   * @generated
   */
  int TERMO_ARITMETICO = 4;

  /**
   * The feature id for the '<em><b>Fator1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_ARITMETICO__FATOR1 = 0;

  /**
   * The feature id for the '<em><b>Outros Fatores</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_ARITMETICO__OUTROS_FATORES = 1;

  /**
   * The number of structural features of the '<em>Termo Aritmetico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_ARITMETICO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroFatorAritmeticoImpl <em>Outro Fator Aritmetico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroFatorAritmeticoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getOutroFatorAritmetico()
   * @generated
   */
  int OUTRO_FATOR_ARITMETICO = 5;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_FATOR_ARITMETICO__OPERADOR = 0;

  /**
   * The feature id for the '<em><b>Fator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_FATOR_ARITMETICO__FATOR = 1;

  /**
   * The number of structural features of the '<em>Outro Fator Aritmetico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_FATOR_ARITMETICO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorAritmeticoImpl <em>Fator Aritmetico</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorAritmeticoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFatorAritmetico()
   * @generated
   */
  int FATOR_ARITMETICO = 6;

  /**
   * The number of structural features of the '<em>Fator Aritmetico</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_ARITMETICO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorNumeroImpl <em>Fator Numero</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorNumeroImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFatorNumero()
   * @generated
   */
  int FATOR_NUMERO = 7;

  /**
   * The feature id for the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_NUMERO__NUMERO = FATOR_ARITMETICO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fator Numero</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_NUMERO_FEATURE_COUNT = FATOR_ARITMETICO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorVariavelImpl <em>Fator Variavel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorVariavelImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFatorVariavel()
   * @generated
   */
  int FATOR_VARIAVEL = 8;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_VARIAVEL__VARIAVEL = FATOR_ARITMETICO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fator Variavel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_VARIAVEL_FEATURE_COUNT = FATOR_ARITMETICO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorSubExpressaoImpl <em>Fator Sub Expressao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorSubExpressaoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFatorSubExpressao()
   * @generated
   */
  int FATOR_SUB_EXPRESSAO = 9;

  /**
   * The feature id for the '<em><b>Expressao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_SUB_EXPRESSAO__EXPRESSAO = FATOR_ARITMETICO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fator Sub Expressao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FATOR_SUB_EXPRESSAO_FEATURE_COUNT = FATOR_ARITMETICO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ExpressaoRelacionalImpl <em>Expressao Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ExpressaoRelacionalImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getExpressaoRelacional()
   * @generated
   */
  int EXPRESSAO_RELACIONAL = 10;

  /**
   * The feature id for the '<em><b>Termo1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL__TERMO1 = 0;

  /**
   * The feature id for the '<em><b>Outros Termos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL__OUTROS_TERMOS = 1;

  /**
   * The number of structural features of the '<em>Expressao Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_RELACIONAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroTermoRelacionalImpl <em>Outro Termo Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroTermoRelacionalImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getOutroTermoRelacional()
   * @generated
   */
  int OUTRO_TERMO_RELACIONAL = 11;

  /**
   * The feature id for the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_RELACIONAL__OPERADOR = 0;

  /**
   * The feature id for the '<em><b>Termo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_RELACIONAL__TERMO = 1;

  /**
   * The number of structural features of the '<em>Outro Termo Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTRO_TERMO_RELACIONAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoRelacionalImpl <em>Termo Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoRelacionalImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getTermoRelacional()
   * @generated
   */
  int TERMO_RELACIONAL = 12;

  /**
   * The number of structural features of the '<em>Termo Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_RELACIONAL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoComparacaoRelacionalImpl <em>Termo Comparacao Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoComparacaoRelacionalImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getTermoComparacaoRelacional()
   * @generated
   */
  int TERMO_COMPARACAO_RELACIONAL = 13;

  /**
   * The feature id for the '<em><b>Expr1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_COMPARACAO_RELACIONAL__EXPR1 = TERMO_RELACIONAL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op Rel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_COMPARACAO_RELACIONAL__OP_REL = TERMO_RELACIONAL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Expr2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_COMPARACAO_RELACIONAL__EXPR2 = TERMO_RELACIONAL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Termo Comparacao Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_COMPARACAO_RELACIONAL_FEATURE_COUNT = TERMO_RELACIONAL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoSubExpressaoRelacionalImpl <em>Termo Sub Expressao Relacional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoSubExpressaoRelacionalImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getTermoSubExpressaoRelacional()
   * @generated
   */
  int TERMO_SUB_EXPRESSAO_RELACIONAL = 14;

  /**
   * The feature id for the '<em><b>Exp Rel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_SUB_EXPRESSAO_RELACIONAL__EXP_REL = TERMO_RELACIONAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Termo Sub Expressao Relacional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMO_SUB_EXPRESSAO_RELACIONAL_FEATURE_COUNT = TERMO_RELACIONAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoImpl <em>Comando</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComando()
   * @generated
   */
  int COMANDO = 15;

  /**
   * The number of structural features of the '<em>Comando</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoAtibuicaoImpl <em>Comando Atibuicao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoAtibuicaoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoAtibuicao()
   * @generated
   */
  int COMANDO_ATIBUICAO = 16;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ATIBUICAO__EXP = COMANDO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ATIBUICAO__VARIAVEL = COMANDO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comando Atibuicao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ATIBUICAO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoEntradaImpl <em>Comando Entrada</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoEntradaImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoEntrada()
   * @generated
   */
  int COMANDO_ENTRADA = 17;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ENTRADA__VARIAVEL = COMANDO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Comando Entrada</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_ENTRADA_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoSaidaImpl <em>Comando Saida</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoSaidaImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoSaida()
   * @generated
   */
  int COMANDO_SAIDA = 18;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_SAIDA__VARIAVEL = COMANDO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Comando Saida</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_SAIDA_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoCondicaoImpl <em>Comando Condicao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoCondicaoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoCondicao()
   * @generated
   */
  int COMANDO_CONDICAO = 19;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_CONDICAO__EXP = COMANDO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cmd1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_CONDICAO__CMD1 = COMANDO_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Cmd2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_CONDICAO__CMD2 = COMANDO_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comando Condicao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_CONDICAO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoRepeticaoImpl <em>Comando Repeticao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoRepeticaoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoRepeticao()
   * @generated
   */
  int COMANDO_REPETICAO = 20;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_REPETICAO__EXP = COMANDO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cmd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_REPETICAO__CMD = COMANDO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comando Repeticao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_REPETICAO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoSubAlgoritmoImpl <em>Comando Sub Algoritmo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoSubAlgoritmoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoSubAlgoritmo()
   * @generated
   */
  int COMANDO_SUB_ALGORITMO = 21;

  /**
   * The feature id for the '<em><b>Comandos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_SUB_ALGORITMO__COMANDOS = COMANDO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Comando Sub Algoritmo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMANDO_SUB_ALGORITMO_FEATURE_COUNT = COMANDO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ChamadaFuncaoImpl <em>Chamada Funcao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ChamadaFuncaoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getChamadaFuncao()
   * @generated
   */
  int CHAMADA_FUNCAO = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAMADA_FUNCAO__NAME = 0;

  /**
   * The feature id for the '<em><b>Argumentos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAMADA_FUNCAO__ARGUMENTOS = 1;

  /**
   * The number of structural features of the '<em>Chamada Funcao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAMADA_FUNCAO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FuncaoImpl <em>Funcao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FuncaoImpl
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFuncao()
   * @generated
   */
  int FUNCAO = 23;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__NAME = 0;

  /**
   * The feature id for the '<em><b>Parametros</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__PARAMETROS = 1;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__TIPO = 2;

  /**
   * The feature id for the '<em><b>Comandos</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO__COMANDOS = 3;

  /**
   * The number of structural features of the '<em>Funcao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCAO_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Programa <em>Programa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programa</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Programa
   * @generated
   */
  EClass getPrograma();

  /**
   * Returns the meta object for the containment reference list '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Programa#getDeclaracoes <em>Declaracoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declaracoes</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Programa#getDeclaracoes()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Declaracoes();

  /**
   * Returns the meta object for the containment reference list '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Programa#getComandos <em>Comandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comandos</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Programa#getComandos()
   * @see #getPrograma()
   * @generated
   */
  EReference getPrograma_Comandos();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao <em>Declaracao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaracao</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao
   * @generated
   */
  EClass getDeclaracao();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao#getName()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Name();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao#getTipo()
   * @see #getDeclaracao()
   * @generated
   */
  EAttribute getDeclaracao_Tipo();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoAritmetica <em>Expressao Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao Aritmetica</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoAritmetica
   * @generated
   */
  EClass getExpressaoAritmetica();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoAritmetica#getTermo1 <em>Termo1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Termo1</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoAritmetica#getTermo1()
   * @see #getExpressaoAritmetica()
   * @generated
   */
  EReference getExpressaoAritmetica_Termo1();

  /**
   * Returns the meta object for the containment reference list '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoAritmetica#getOutrosTermos <em>Outros Termos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Outros Termos</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoAritmetica#getOutrosTermos()
   * @see #getExpressaoAritmetica()
   * @generated
   */
  EReference getExpressaoAritmetica_OutrosTermos();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoAritmetico <em>Outro Termo Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outro Termo Aritmetico</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoAritmetico
   * @generated
   */
  EClass getOutroTermoAritmetico();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoAritmetico#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoAritmetico#getOperador()
   * @see #getOutroTermoAritmetico()
   * @generated
   */
  EAttribute getOutroTermoAritmetico_Operador();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoAritmetico#getTermo <em>Termo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Termo</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoAritmetico#getTermo()
   * @see #getOutroTermoAritmetico()
   * @generated
   */
  EReference getOutroTermoAritmetico_Termo();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoAritmetico <em>Termo Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Aritmetico</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoAritmetico
   * @generated
   */
  EClass getTermoAritmetico();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoAritmetico#getFator1 <em>Fator1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fator1</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoAritmetico#getFator1()
   * @see #getTermoAritmetico()
   * @generated
   */
  EReference getTermoAritmetico_Fator1();

  /**
   * Returns the meta object for the containment reference list '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoAritmetico#getOutrosFatores <em>Outros Fatores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Outros Fatores</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoAritmetico#getOutrosFatores()
   * @see #getTermoAritmetico()
   * @generated
   */
  EReference getTermoAritmetico_OutrosFatores();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroFatorAritmetico <em>Outro Fator Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outro Fator Aritmetico</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroFatorAritmetico
   * @generated
   */
  EClass getOutroFatorAritmetico();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroFatorAritmetico#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroFatorAritmetico#getOperador()
   * @see #getOutroFatorAritmetico()
   * @generated
   */
  EAttribute getOutroFatorAritmetico_Operador();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroFatorAritmetico#getFator <em>Fator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fator</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroFatorAritmetico#getFator()
   * @see #getOutroFatorAritmetico()
   * @generated
   */
  EReference getOutroFatorAritmetico_Fator();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.FatorAritmetico <em>Fator Aritmetico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Aritmetico</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.FatorAritmetico
   * @generated
   */
  EClass getFatorAritmetico();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.FatorNumero <em>Fator Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Numero</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.FatorNumero
   * @generated
   */
  EClass getFatorNumero();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.FatorNumero#getNumero <em>Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.FatorNumero#getNumero()
   * @see #getFatorNumero()
   * @generated
   */
  EAttribute getFatorNumero_Numero();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.FatorVariavel <em>Fator Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Variavel</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.FatorVariavel
   * @generated
   */
  EClass getFatorVariavel();

  /**
   * Returns the meta object for the reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.FatorVariavel#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variavel</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.FatorVariavel#getVariavel()
   * @see #getFatorVariavel()
   * @generated
   */
  EReference getFatorVariavel_Variavel();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.FatorSubExpressao <em>Fator Sub Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fator Sub Expressao</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.FatorSubExpressao
   * @generated
   */
  EClass getFatorSubExpressao();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.FatorSubExpressao#getExpressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expressao</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.FatorSubExpressao#getExpressao()
   * @see #getFatorSubExpressao()
   * @generated
   */
  EReference getFatorSubExpressao_Expressao();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional <em>Expressao Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao Relacional</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional
   * @generated
   */
  EClass getExpressaoRelacional();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional#getTermo1 <em>Termo1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Termo1</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional#getTermo1()
   * @see #getExpressaoRelacional()
   * @generated
   */
  EReference getExpressaoRelacional_Termo1();

  /**
   * Returns the meta object for the containment reference list '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional#getOutrosTermos <em>Outros Termos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Outros Termos</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional#getOutrosTermos()
   * @see #getExpressaoRelacional()
   * @generated
   */
  EReference getExpressaoRelacional_OutrosTermos();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional <em>Outro Termo Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outro Termo Relacional</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional
   * @generated
   */
  EClass getOutroTermoRelacional();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional#getOperador <em>Operador</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operador</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional#getOperador()
   * @see #getOutroTermoRelacional()
   * @generated
   */
  EAttribute getOutroTermoRelacional_Operador();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional#getTermo <em>Termo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Termo</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional#getTermo()
   * @see #getOutroTermoRelacional()
   * @generated
   */
  EReference getOutroTermoRelacional_Termo();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoRelacional <em>Termo Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Relacional</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoRelacional
   * @generated
   */
  EClass getTermoRelacional();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional <em>Termo Comparacao Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Comparacao Relacional</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional
   * @generated
   */
  EClass getTermoComparacaoRelacional();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional#getExpr1 <em>Expr1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr1</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional#getExpr1()
   * @see #getTermoComparacaoRelacional()
   * @generated
   */
  EReference getTermoComparacaoRelacional_Expr1();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional#getOpRel <em>Op Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op Rel</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional#getOpRel()
   * @see #getTermoComparacaoRelacional()
   * @generated
   */
  EAttribute getTermoComparacaoRelacional_OpRel();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional#getExpr2 <em>Expr2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr2</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional#getExpr2()
   * @see #getTermoComparacaoRelacional()
   * @generated
   */
  EReference getTermoComparacaoRelacional_Expr2();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoSubExpressaoRelacional <em>Termo Sub Expressao Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termo Sub Expressao Relacional</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoSubExpressaoRelacional
   * @generated
   */
  EClass getTermoSubExpressaoRelacional();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoSubExpressaoRelacional#getExpRel <em>Exp Rel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp Rel</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.TermoSubExpressaoRelacional#getExpRel()
   * @see #getTermoSubExpressaoRelacional()
   * @generated
   */
  EReference getTermoSubExpressaoRelacional_ExpRel();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Comando <em>Comando</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Comando
   * @generated
   */
  EClass getComando();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoAtibuicao <em>Comando Atibuicao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Atibuicao</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoAtibuicao
   * @generated
   */
  EClass getComandoAtibuicao();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoAtibuicao#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoAtibuicao#getExp()
   * @see #getComandoAtibuicao()
   * @generated
   */
  EReference getComandoAtibuicao_Exp();

  /**
   * Returns the meta object for the reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoAtibuicao#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variavel</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoAtibuicao#getVariavel()
   * @see #getComandoAtibuicao()
   * @generated
   */
  EReference getComandoAtibuicao_Variavel();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoEntrada <em>Comando Entrada</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Entrada</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoEntrada
   * @generated
   */
  EClass getComandoEntrada();

  /**
   * Returns the meta object for the reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoEntrada#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variavel</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoEntrada#getVariavel()
   * @see #getComandoEntrada()
   * @generated
   */
  EReference getComandoEntrada_Variavel();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSaida <em>Comando Saida</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Saida</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSaida
   * @generated
   */
  EClass getComandoSaida();

  /**
   * Returns the meta object for the reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSaida#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variavel</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSaida#getVariavel()
   * @see #getComandoSaida()
   * @generated
   */
  EReference getComandoSaida_Variavel();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao <em>Comando Condicao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Condicao</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao
   * @generated
   */
  EClass getComandoCondicao();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao#getExp()
   * @see #getComandoCondicao()
   * @generated
   */
  EReference getComandoCondicao_Exp();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao#getCmd1 <em>Cmd1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmd1</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao#getCmd1()
   * @see #getComandoCondicao()
   * @generated
   */
  EReference getComandoCondicao_Cmd1();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao#getCmd2 <em>Cmd2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmd2</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao#getCmd2()
   * @see #getComandoCondicao()
   * @generated
   */
  EReference getComandoCondicao_Cmd2();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoRepeticao <em>Comando Repeticao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Repeticao</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoRepeticao
   * @generated
   */
  EClass getComandoRepeticao();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoRepeticao#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoRepeticao#getExp()
   * @see #getComandoRepeticao()
   * @generated
   */
  EReference getComandoRepeticao_Exp();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoRepeticao#getCmd <em>Cmd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmd</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoRepeticao#getCmd()
   * @see #getComandoRepeticao()
   * @generated
   */
  EReference getComandoRepeticao_Cmd();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSubAlgoritmo <em>Comando Sub Algoritmo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comando Sub Algoritmo</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSubAlgoritmo
   * @generated
   */
  EClass getComandoSubAlgoritmo();

  /**
   * Returns the meta object for the containment reference list '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSubAlgoritmo#getComandos <em>Comandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Comandos</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSubAlgoritmo#getComandos()
   * @see #getComandoSubAlgoritmo()
   * @generated
   */
  EReference getComandoSubAlgoritmo_Comandos();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ChamadaFuncao <em>Chamada Funcao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chamada Funcao</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ChamadaFuncao
   * @generated
   */
  EClass getChamadaFuncao();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ChamadaFuncao#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ChamadaFuncao#getName()
   * @see #getChamadaFuncao()
   * @generated
   */
  EAttribute getChamadaFuncao_Name();

  /**
   * Returns the meta object for the containment reference list '{@link br.compiladores.jhonatan.jlanguage.jlanguage.ChamadaFuncao#getArgumentos <em>Argumentos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Argumentos</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.ChamadaFuncao#getArgumentos()
   * @see #getChamadaFuncao()
   * @generated
   */
  EReference getChamadaFuncao_Argumentos();

  /**
   * Returns the meta object for class '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao <em>Funcao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Funcao</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Funcao
   * @generated
   */
  EClass getFuncao();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getName()
   * @see #getFuncao()
   * @generated
   */
  EAttribute getFuncao_Name();

  /**
   * Returns the meta object for the containment reference list '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getParametros <em>Parametros</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametros</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getParametros()
   * @see #getFuncao()
   * @generated
   */
  EReference getFuncao_Parametros();

  /**
   * Returns the meta object for the attribute '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getTipo()
   * @see #getFuncao()
   * @generated
   */
  EAttribute getFuncao_Tipo();

  /**
   * Returns the meta object for the containment reference '{@link br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getComandos <em>Comandos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Comandos</em>'.
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.Funcao#getComandos()
   * @see #getFuncao()
   * @generated
   */
  EReference getFuncao_Comandos();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JlanguageFactory getJlanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ProgramaImpl <em>Programa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ProgramaImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getPrograma()
     * @generated
     */
    EClass PROGRAMA = eINSTANCE.getPrograma();

    /**
     * The meta object literal for the '<em><b>Declaracoes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__DECLARACOES = eINSTANCE.getPrograma_Declaracoes();

    /**
     * The meta object literal for the '<em><b>Comandos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__COMANDOS = eINSTANCE.getPrograma_Comandos();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.DeclaracaoImpl <em>Declaracao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.DeclaracaoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getDeclaracao()
     * @generated
     */
    EClass DECLARACAO = eINSTANCE.getDeclaracao();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__NAME = eINSTANCE.getDeclaracao_Name();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARACAO__TIPO = eINSTANCE.getDeclaracao_Tipo();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ExpressaoAritmeticaImpl <em>Expressao Aritmetica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ExpressaoAritmeticaImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getExpressaoAritmetica()
     * @generated
     */
    EClass EXPRESSAO_ARITMETICA = eINSTANCE.getExpressaoAritmetica();

    /**
     * The meta object literal for the '<em><b>Termo1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_ARITMETICA__TERMO1 = eINSTANCE.getExpressaoAritmetica_Termo1();

    /**
     * The meta object literal for the '<em><b>Outros Termos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_ARITMETICA__OUTROS_TERMOS = eINSTANCE.getExpressaoAritmetica_OutrosTermos();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroTermoAritmeticoImpl <em>Outro Termo Aritmetico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroTermoAritmeticoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getOutroTermoAritmetico()
     * @generated
     */
    EClass OUTRO_TERMO_ARITMETICO = eINSTANCE.getOutroTermoAritmetico();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTRO_TERMO_ARITMETICO__OPERADOR = eINSTANCE.getOutroTermoAritmetico_Operador();

    /**
     * The meta object literal for the '<em><b>Termo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTRO_TERMO_ARITMETICO__TERMO = eINSTANCE.getOutroTermoAritmetico_Termo();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoAritmeticoImpl <em>Termo Aritmetico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoAritmeticoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getTermoAritmetico()
     * @generated
     */
    EClass TERMO_ARITMETICO = eINSTANCE.getTermoAritmetico();

    /**
     * The meta object literal for the '<em><b>Fator1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_ARITMETICO__FATOR1 = eINSTANCE.getTermoAritmetico_Fator1();

    /**
     * The meta object literal for the '<em><b>Outros Fatores</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_ARITMETICO__OUTROS_FATORES = eINSTANCE.getTermoAritmetico_OutrosFatores();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroFatorAritmeticoImpl <em>Outro Fator Aritmetico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroFatorAritmeticoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getOutroFatorAritmetico()
     * @generated
     */
    EClass OUTRO_FATOR_ARITMETICO = eINSTANCE.getOutroFatorAritmetico();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTRO_FATOR_ARITMETICO__OPERADOR = eINSTANCE.getOutroFatorAritmetico_Operador();

    /**
     * The meta object literal for the '<em><b>Fator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTRO_FATOR_ARITMETICO__FATOR = eINSTANCE.getOutroFatorAritmetico_Fator();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorAritmeticoImpl <em>Fator Aritmetico</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorAritmeticoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFatorAritmetico()
     * @generated
     */
    EClass FATOR_ARITMETICO = eINSTANCE.getFatorAritmetico();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorNumeroImpl <em>Fator Numero</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorNumeroImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFatorNumero()
     * @generated
     */
    EClass FATOR_NUMERO = eINSTANCE.getFatorNumero();

    /**
     * The meta object literal for the '<em><b>Numero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FATOR_NUMERO__NUMERO = eINSTANCE.getFatorNumero_Numero();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorVariavelImpl <em>Fator Variavel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorVariavelImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFatorVariavel()
     * @generated
     */
    EClass FATOR_VARIAVEL = eINSTANCE.getFatorVariavel();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FATOR_VARIAVEL__VARIAVEL = eINSTANCE.getFatorVariavel_Variavel();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorSubExpressaoImpl <em>Fator Sub Expressao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FatorSubExpressaoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFatorSubExpressao()
     * @generated
     */
    EClass FATOR_SUB_EXPRESSAO = eINSTANCE.getFatorSubExpressao();

    /**
     * The meta object literal for the '<em><b>Expressao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FATOR_SUB_EXPRESSAO__EXPRESSAO = eINSTANCE.getFatorSubExpressao_Expressao();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ExpressaoRelacionalImpl <em>Expressao Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ExpressaoRelacionalImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getExpressaoRelacional()
     * @generated
     */
    EClass EXPRESSAO_RELACIONAL = eINSTANCE.getExpressaoRelacional();

    /**
     * The meta object literal for the '<em><b>Termo1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_RELACIONAL__TERMO1 = eINSTANCE.getExpressaoRelacional_Termo1();

    /**
     * The meta object literal for the '<em><b>Outros Termos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO_RELACIONAL__OUTROS_TERMOS = eINSTANCE.getExpressaoRelacional_OutrosTermos();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroTermoRelacionalImpl <em>Outro Termo Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.OutroTermoRelacionalImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getOutroTermoRelacional()
     * @generated
     */
    EClass OUTRO_TERMO_RELACIONAL = eINSTANCE.getOutroTermoRelacional();

    /**
     * The meta object literal for the '<em><b>Operador</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTRO_TERMO_RELACIONAL__OPERADOR = eINSTANCE.getOutroTermoRelacional_Operador();

    /**
     * The meta object literal for the '<em><b>Termo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTRO_TERMO_RELACIONAL__TERMO = eINSTANCE.getOutroTermoRelacional_Termo();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoRelacionalImpl <em>Termo Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoRelacionalImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getTermoRelacional()
     * @generated
     */
    EClass TERMO_RELACIONAL = eINSTANCE.getTermoRelacional();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoComparacaoRelacionalImpl <em>Termo Comparacao Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoComparacaoRelacionalImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getTermoComparacaoRelacional()
     * @generated
     */
    EClass TERMO_COMPARACAO_RELACIONAL = eINSTANCE.getTermoComparacaoRelacional();

    /**
     * The meta object literal for the '<em><b>Expr1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_COMPARACAO_RELACIONAL__EXPR1 = eINSTANCE.getTermoComparacaoRelacional_Expr1();

    /**
     * The meta object literal for the '<em><b>Op Rel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERMO_COMPARACAO_RELACIONAL__OP_REL = eINSTANCE.getTermoComparacaoRelacional_OpRel();

    /**
     * The meta object literal for the '<em><b>Expr2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_COMPARACAO_RELACIONAL__EXPR2 = eINSTANCE.getTermoComparacaoRelacional_Expr2();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoSubExpressaoRelacionalImpl <em>Termo Sub Expressao Relacional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.TermoSubExpressaoRelacionalImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getTermoSubExpressaoRelacional()
     * @generated
     */
    EClass TERMO_SUB_EXPRESSAO_RELACIONAL = eINSTANCE.getTermoSubExpressaoRelacional();

    /**
     * The meta object literal for the '<em><b>Exp Rel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMO_SUB_EXPRESSAO_RELACIONAL__EXP_REL = eINSTANCE.getTermoSubExpressaoRelacional_ExpRel();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoImpl <em>Comando</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComando()
     * @generated
     */
    EClass COMANDO = eINSTANCE.getComando();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoAtibuicaoImpl <em>Comando Atibuicao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoAtibuicaoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoAtibuicao()
     * @generated
     */
    EClass COMANDO_ATIBUICAO = eINSTANCE.getComandoAtibuicao();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_ATIBUICAO__EXP = eINSTANCE.getComandoAtibuicao_Exp();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_ATIBUICAO__VARIAVEL = eINSTANCE.getComandoAtibuicao_Variavel();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoEntradaImpl <em>Comando Entrada</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoEntradaImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoEntrada()
     * @generated
     */
    EClass COMANDO_ENTRADA = eINSTANCE.getComandoEntrada();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_ENTRADA__VARIAVEL = eINSTANCE.getComandoEntrada_Variavel();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoSaidaImpl <em>Comando Saida</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoSaidaImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoSaida()
     * @generated
     */
    EClass COMANDO_SAIDA = eINSTANCE.getComandoSaida();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_SAIDA__VARIAVEL = eINSTANCE.getComandoSaida_Variavel();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoCondicaoImpl <em>Comando Condicao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoCondicaoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoCondicao()
     * @generated
     */
    EClass COMANDO_CONDICAO = eINSTANCE.getComandoCondicao();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_CONDICAO__EXP = eINSTANCE.getComandoCondicao_Exp();

    /**
     * The meta object literal for the '<em><b>Cmd1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_CONDICAO__CMD1 = eINSTANCE.getComandoCondicao_Cmd1();

    /**
     * The meta object literal for the '<em><b>Cmd2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_CONDICAO__CMD2 = eINSTANCE.getComandoCondicao_Cmd2();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoRepeticaoImpl <em>Comando Repeticao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoRepeticaoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoRepeticao()
     * @generated
     */
    EClass COMANDO_REPETICAO = eINSTANCE.getComandoRepeticao();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_REPETICAO__EXP = eINSTANCE.getComandoRepeticao_Exp();

    /**
     * The meta object literal for the '<em><b>Cmd</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_REPETICAO__CMD = eINSTANCE.getComandoRepeticao_Cmd();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoSubAlgoritmoImpl <em>Comando Sub Algoritmo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ComandoSubAlgoritmoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getComandoSubAlgoritmo()
     * @generated
     */
    EClass COMANDO_SUB_ALGORITMO = eINSTANCE.getComandoSubAlgoritmo();

    /**
     * The meta object literal for the '<em><b>Comandos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMANDO_SUB_ALGORITMO__COMANDOS = eINSTANCE.getComandoSubAlgoritmo_Comandos();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.ChamadaFuncaoImpl <em>Chamada Funcao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.ChamadaFuncaoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getChamadaFuncao()
     * @generated
     */
    EClass CHAMADA_FUNCAO = eINSTANCE.getChamadaFuncao();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHAMADA_FUNCAO__NAME = eINSTANCE.getChamadaFuncao_Name();

    /**
     * The meta object literal for the '<em><b>Argumentos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHAMADA_FUNCAO__ARGUMENTOS = eINSTANCE.getChamadaFuncao_Argumentos();

    /**
     * The meta object literal for the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.impl.FuncaoImpl <em>Funcao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.FuncaoImpl
     * @see br.compiladores.jhonatan.jlanguage.jlanguage.impl.JlanguagePackageImpl#getFuncao()
     * @generated
     */
    EClass FUNCAO = eINSTANCE.getFuncao();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCAO__NAME = eINSTANCE.getFuncao_Name();

    /**
     * The meta object literal for the '<em><b>Parametros</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCAO__PARAMETROS = eINSTANCE.getFuncao_Parametros();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCAO__TIPO = eINSTANCE.getFuncao_Tipo();

    /**
     * The meta object literal for the '<em><b>Comandos</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCAO__COMANDOS = eINSTANCE.getFuncao_Comandos();

  }

} //JlanguagePackage
