/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outro Termo Relacional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional#getOperador <em>Operador</em>}</li>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional#getTermo <em>Termo</em>}</li>
 * </ul>
 *
 * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getOutroTermoRelacional()
 * @model
 * @generated
 */
public interface OutroTermoRelacional extends EObject
{
  /**
   * Returns the value of the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador</em>' attribute.
   * @see #setOperador(String)
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getOutroTermoRelacional_Operador()
   * @model
   * @generated
   */
  String getOperador();

  /**
   * Sets the value of the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional#getOperador <em>Operador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operador</em>' attribute.
   * @see #getOperador()
   * @generated
   */
  void setOperador(String value);

  /**
   * Returns the value of the '<em><b>Termo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termo</em>' containment reference.
   * @see #setTermo(TermoRelacional)
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getOutroTermoRelacional_Termo()
   * @model containment="true"
   * @generated
   */
  TermoRelacional getTermo();

  /**
   * Sets the value of the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional#getTermo <em>Termo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Termo</em>' containment reference.
   * @see #getTermo()
   * @generated
   */
  void setTermo(TermoRelacional value);

} // OutroTermoRelacional
