/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termo Relacional</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getTermoRelacional()
 * @model
 * @generated
 */
public interface TermoRelacional extends EObject
{
} // TermoRelacional
