/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.jlanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termo Sub Expressao Relacional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoSubExpressaoRelacional#getExpRel <em>Exp Rel</em>}</li>
 * </ul>
 *
 * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getTermoSubExpressaoRelacional()
 * @model
 * @generated
 */
public interface TermoSubExpressaoRelacional extends TermoRelacional
{
  /**
   * Returns the value of the '<em><b>Exp Rel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp Rel</em>' containment reference.
   * @see #setExpRel(ExpressaoRelacional)
   * @see br.compiladores.jhonatan.jlanguage.jlanguage.JlanguagePackage#getTermoSubExpressaoRelacional_ExpRel()
   * @model containment="true"
   * @generated
   */
  ExpressaoRelacional getExpRel();

  /**
   * Sets the value of the '{@link br.compiladores.jhonatan.jlanguage.jlanguage.TermoSubExpressaoRelacional#getExpRel <em>Exp Rel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp Rel</em>' containment reference.
   * @see #getExpRel()
   * @generated
   */
  void setExpRel(ExpressaoRelacional value);

} // TermoSubExpressaoRelacional
