/*
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.ide;


/**
 * Use this class to register ide components.
 */
public class JlanguageIdeModule extends AbstractJlanguageIdeModule {
}
