/**
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.generator;

import br.compiladores.jhonatan.jlanguage.jlanguage.Comando;
import br.compiladores.jhonatan.jlanguage.jlanguage.ComandoAtibuicao;
import br.compiladores.jhonatan.jlanguage.jlanguage.ComandoCondicao;
import br.compiladores.jhonatan.jlanguage.jlanguage.ComandoEntrada;
import br.compiladores.jhonatan.jlanguage.jlanguage.ComandoRepeticao;
import br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSaida;
import br.compiladores.jhonatan.jlanguage.jlanguage.ComandoSubAlgoritmo;
import br.compiladores.jhonatan.jlanguage.jlanguage.Declaracao;
import br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoAritmetica;
import br.compiladores.jhonatan.jlanguage.jlanguage.ExpressaoRelacional;
import br.compiladores.jhonatan.jlanguage.jlanguage.FatorAritmetico;
import br.compiladores.jhonatan.jlanguage.jlanguage.FatorNumero;
import br.compiladores.jhonatan.jlanguage.jlanguage.FatorSubExpressao;
import br.compiladores.jhonatan.jlanguage.jlanguage.FatorVariavel;
import br.compiladores.jhonatan.jlanguage.jlanguage.OutroFatorAritmetico;
import br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoAritmetico;
import br.compiladores.jhonatan.jlanguage.jlanguage.OutroTermoRelacional;
import br.compiladores.jhonatan.jlanguage.jlanguage.Programa;
import br.compiladores.jhonatan.jlanguage.jlanguage.TermoAritmetico;
import br.compiladores.jhonatan.jlanguage.jlanguage.TermoComparacaoRelacional;
import br.compiladores.jhonatan.jlanguage.jlanguage.TermoRelacional;
import br.compiladores.jhonatan.jlanguage.jlanguage.TermoSubExpressaoRelacional;
import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import java.util.Arrays;
import java.util.function.Consumer;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class JlanguageGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Iterable<Programa> _filter = Iterables.<Programa>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Programa.class);
    for (final Programa p : _filter) {
      fsa.generateFile("Programa.java", this.compilePrograma(p));
    }
  }

  public CharSequence compilePrograma(final Programa p) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public class Programa{");
    _builder.newLine();
    {
      EList<Declaracao> _declaracoes = p.getDeclaracoes();
      for(final Declaracao d : _declaracoes) {
        _builder.append("\t");
        _builder.append("static ");
        String _tipo = this.getTipo(d);
        _builder.append(_tipo, "\t");
        _builder.append(" ");
        String _name = d.getName();
        _builder.append(_name, "\t");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static void main(String args[]){");
    _builder.newLine();
    {
      EList<Comando> _comandos = p.getComandos();
      for(final Comando c : _comandos) {
        _builder.append("\t\t");
        CharSequence _compileComando = this.compileComando(c);
        _builder.append(_compileComando, "\t\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public String getTipo(final Declaracao d) {
    String _tipo = d.getTipo();
    boolean _equals = Objects.equal(_tipo, "REAL");
    if (_equals) {
      return "double";
    }
    String _tipo_1 = d.getTipo();
    boolean _equals_1 = Objects.equal(_tipo_1, "TEXTO");
    if (_equals_1) {
      return "string";
    }
    String _tipo_2 = d.getTipo();
    boolean _equals_2 = Objects.equal(_tipo_2, "BOOLEANO");
    if (_equals_2) {
      return "boolean";
    }
    return "int";
  }

  protected CharSequence _compileComando(final ComandoAtibuicao c) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = c.getVariavel().getName();
    _builder.append(_name);
    _builder.append(" = ");
    StringConcatenation _compileExpressao = this.compileExpressao(c.getExp());
    _builder.append(_compileExpressao);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileComando(final ComandoEntrada c) {
    StringConcatenation _builder = new StringConcatenation();
    {
      String _tipo = c.getVariavel().getTipo();
      boolean _equals = Objects.equal(_tipo, "INTEIRO");
      if (_equals) {
        String _name = c.getVariavel().getName();
        _builder.append(_name);
        _builder.append(" = Integer.parseInt(System.console().readLine());");
        _builder.newLineIfNotEmpty();
      } else {
        String _tipo_1 = c.getVariavel().getTipo();
        boolean _equals_1 = Objects.equal(_tipo_1, "REAL");
        if (_equals_1) {
          String _name_1 = c.getVariavel().getName();
          _builder.append(_name_1);
          _builder.append(" = Double.parseDouble(System.console().readLine());");
          _builder.newLineIfNotEmpty();
        } else {
          String _tipo_2 = c.getVariavel().getTipo();
          boolean _equals_2 = Objects.equal(_tipo_2, "TEXTO");
          if (_equals_2) {
            String _name_2 = c.getVariavel().getName();
            _builder.append(_name_2);
            _builder.append(" = System.console().readLine();");
            _builder.newLineIfNotEmpty();
          } else {
            String _tipo_3 = c.getVariavel().getTipo();
            boolean _equals_3 = Objects.equal(_tipo_3, "BOOLEANO");
            if (_equals_3) {
              String _name_3 = c.getVariavel().getName();
              _builder.append(_name_3);
              _builder.append(" = Boolean.parseBoolean(System.console().readLine());");
              _builder.newLineIfNotEmpty();
            }
          }
        }
      }
    }
    return _builder;
  }

  protected CharSequence _compileComando(final ComandoSaida c) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("System.out.println(");
    String _name = c.getVariavel().getName();
    _builder.append(_name);
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileComando(final ComandoCondicao c) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("if(");
    StringConcatenation _compileExpressaoRelacional = this.compileExpressaoRelacional(c.getExp());
    _builder.append(_compileExpressaoRelacional);
    _builder.append(") ");
    Object _compileComando = this.compileComando(c.getCmd1());
    _builder.append(_compileComando);
    _builder.newLineIfNotEmpty();
    {
      Comando _cmd2 = c.getCmd2();
      boolean _tripleNotEquals = (_cmd2 != null);
      if (_tripleNotEquals) {
        _builder.append("else ");
        Object _compileComando_1 = this.compileComando(c.getCmd2());
        _builder.append(_compileComando_1);
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileComando(final ComandoRepeticao c) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("while(");
    StringConcatenation _compileExpressaoRelacional = this.compileExpressaoRelacional(c.getExp());
    _builder.append(_compileExpressaoRelacional);
    _builder.append(") ");
    Object _compileComando = this.compileComando(c.getCmd());
    _builder.append(_compileComando);
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _compileComando(final ComandoSubAlgoritmo cs) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("{");
    _builder.newLine();
    {
      EList<Comando> _comandos = cs.getComandos();
      for(final Comando c : _comandos) {
        _builder.append("\t");
        Object _compileComando = this.compileComando(c);
        _builder.append(_compileComando, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public StringConcatenation compileExpressao(final ExpressaoAritmetica e) {
    final StringConcatenation ret = new StringConcatenation();
    ret.append(this.compileTermo(e.getTermo1()));
    final Consumer<OutroTermoAritmetico> _function = (OutroTermoAritmetico ot) -> {
      String _operador = ot.getOperador();
      String _plus = (" " + _operador);
      String _plus_1 = (_plus + " ");
      StringConcatenation _compileTermo = this.compileTermo(ot.getTermo());
      String _plus_2 = (_plus_1 + _compileTermo);
      ret.append(_plus_2);
    };
    e.getOutrosTermos().forEach(_function);
    return ret;
  }

  public StringConcatenation compileTermo(final TermoAritmetico t) {
    final StringConcatenation ret = new StringConcatenation();
    ret.append(this.compileFator(t.getFator1()));
    final Consumer<OutroFatorAritmetico> _function = (OutroFatorAritmetico of) -> {
      String _operador = of.getOperador();
      String _plus = (" " + _operador);
      String _plus_1 = (_plus + " ");
      CharSequence _compileFator = this.compileFator(of.getFator());
      String _plus_2 = (_plus_1 + _compileFator);
      ret.append(_plus_2);
    };
    t.getOutrosFatores().forEach(_function);
    return ret;
  }

  protected CharSequence _compileFator(final FatorNumero fn) {
    StringConcatenation _builder = new StringConcatenation();
    int _numero = fn.getNumero();
    _builder.append(_numero);
    return _builder;
  }

  protected CharSequence _compileFator(final FatorVariavel fv) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = fv.getVariavel().getName();
    _builder.append(_name);
    return _builder;
  }

  protected CharSequence _compileFator(final FatorSubExpressao fse) {
    StringConcatenation _builder = new StringConcatenation();
    Object _compileExpressao = this.compileExpressao(fse.getExpressao());
    _builder.append(_compileExpressao);
    return _builder;
  }

  public StringConcatenation compileExpressaoRelacional(final ExpressaoRelacional e) {
    final StringConcatenation ret = new StringConcatenation();
    ret.append(this.compileTermoRelacional(e.getTermo1()));
    final Consumer<OutroTermoRelacional> _function = (OutroTermoRelacional ot) -> {
      String _compileOperadorBooleno = this.compileOperadorBooleno(ot.getOperador());
      String _plus = (" " + _compileOperadorBooleno);
      String _plus_1 = (_plus + " ");
      CharSequence _compileTermoRelacional = this.compileTermoRelacional(ot.getTermo());
      String _plus_2 = (_plus_1 + _compileTermoRelacional);
      ret.append(_plus_2);
    };
    e.getOutrosTermos().forEach(_function);
    return ret;
  }

  public String compileOperadorBooleno(final String s) {
    boolean _equals = Objects.equal(s, "E");
    if (_equals) {
      return "&&";
    } else {
      return "||";
    }
  }

  protected CharSequence _compileTermoRelacional(final TermoComparacaoRelacional tcr) {
    StringConcatenation _compileExpressao = this.compileExpressao(tcr.getExpr1());
    String _plus = (_compileExpressao + " ");
    String _compileOperadorRelacional = this.compileOperadorRelacional(tcr.getOpRel());
    String _plus_1 = (_plus + _compileOperadorRelacional);
    String _plus_2 = (_plus_1 + " ");
    StringConcatenation _compileExpressao_1 = this.compileExpressao(tcr.getExpr2());
    return (_plus_2 + _compileExpressao_1);
  }

  protected CharSequence _compileTermoRelacional(final TermoSubExpressaoRelacional tser) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("(");
    ExpressaoRelacional _expRel = tser.getExpRel();
    _builder.append(_expRel);
    _builder.append(")");
    return _builder;
  }

  public String compileOperadorRelacional(final String s) {
    boolean _equals = Objects.equal(s, "<");
    if (_equals) {
      return "<";
    } else {
      boolean _equals_1 = Objects.equal(s, "<=");
      if (_equals_1) {
        return "<=";
      } else {
        boolean _equals_2 = Objects.equal(s, ">");
        if (_equals_2) {
          return ">";
        } else {
          boolean _equals_3 = Objects.equal(s, ">=");
          if (_equals_3) {
            return ">=";
          } else {
            boolean _equals_4 = Objects.equal(s, "<>");
            if (_equals_4) {
              return "!=";
            } else {
              boolean _equals_5 = Objects.equal(s, "=");
              if (_equals_5) {
                return "==";
              }
            }
          }
        }
      }
    }
    return null;
  }

  public CharSequence compileComando(final Comando c) {
    if (c instanceof ComandoAtibuicao) {
      return _compileComando((ComandoAtibuicao)c);
    } else if (c instanceof ComandoCondicao) {
      return _compileComando((ComandoCondicao)c);
    } else if (c instanceof ComandoEntrada) {
      return _compileComando((ComandoEntrada)c);
    } else if (c instanceof ComandoRepeticao) {
      return _compileComando((ComandoRepeticao)c);
    } else if (c instanceof ComandoSaida) {
      return _compileComando((ComandoSaida)c);
    } else if (c instanceof ComandoSubAlgoritmo) {
      return _compileComando((ComandoSubAlgoritmo)c);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(c).toString());
    }
  }

  public CharSequence compileFator(final FatorAritmetico fn) {
    if (fn instanceof FatorNumero) {
      return _compileFator((FatorNumero)fn);
    } else if (fn instanceof FatorSubExpressao) {
      return _compileFator((FatorSubExpressao)fn);
    } else if (fn instanceof FatorVariavel) {
      return _compileFator((FatorVariavel)fn);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(fn).toString());
    }
  }

  public CharSequence compileTermoRelacional(final TermoRelacional tcr) {
    if (tcr instanceof TermoComparacaoRelacional) {
      return _compileTermoRelacional((TermoComparacaoRelacional)tcr);
    } else if (tcr instanceof TermoSubExpressaoRelacional) {
      return _compileTermoRelacional((TermoSubExpressaoRelacional)tcr);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(tcr).toString());
    }
  }
}
