/*
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JlanguageUiModule extends AbstractJlanguageUiModule {

	public JlanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
