/*
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.ui;

import br.compiladores.jhonatan.jlanguage.ui.internal.JlanguageActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JlanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(JlanguageActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		JlanguageActivator activator = JlanguageActivator.getInstance();
		return activator != null ? activator.getInjector(JlanguageActivator.BR_COMPILADORES_JHONATAN_JLANGUAGE_JLANGUAGE) : null;
	}

}
