/*
 * generated by Xtext 2.30.0-SNAPSHOT
 */
package br.compiladores.jhonatan.jlanguage.parser.antlr;

import br.compiladores.jhonatan.jlanguage.parser.antlr.internal.InternalJlanguageParser;
import br.compiladores.jhonatan.jlanguage.services.JlanguageGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class JlanguageParser extends AbstractAntlrParser {

	@Inject
	private JlanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJlanguageParser createParser(XtextTokenStream stream) {
		return new InternalJlanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Programa";
	}

	public JlanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JlanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
